# Since salt/salt states aren't a language proper, this is a hackaround for now
language: python
python:
- '2.7'

before_install:
  # Remove existing zmq3 repo like salt-bootstrap is doing
  - sudo apt-get remove -y -o DPkg::Options::=--force-confold --purge libzmq3
  - sudo apt-get autoremove -y -o DPkg::Options::=--force-confold --purge
  - sudo ls -lah /etc/apt/sources.list.d/
  - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  # Refresh
  - sudo apt-get update -y
  # Install salt minion on the same box
  - curl -L https://bootstrap.saltstack.com -o install_salt.sh
  - sudo sh install_salt.sh
  # Set up our installation bits
  - sudo mkdir -p /srv/salt/states
  - sudo cp .travis/minion /etc/salt/minion

install:
  # Copy the states and restart
  - sudo cp -r . /srv/salt/states
  - sudo service salt-minion restart

  # If anything bad happened on restarting the minion,
  # we'll want to see the logs
  - sudo cat /var/log/salt/*

script:
  - sudo salt-call state.show_lowstate --local --retcode-passthrough

notifications:
  email: false
