# Since salt/salt states aren't a language proper, this is a hackaround for now
language: python
python:
- '2.7'

before_install:
  # Remove existing zmq3 from travis runners like salt-bootstrap is doing
  - sudo apt-get remove -y -o DPkg::Options::=--force-confold --purge libzmq3
  - sudo apt-get autoremove -y -o DPkg::Options::=--force-confold --purge
  - sudo ls -lah /etc/apt/sources.list.d/
  - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  # Install salt minion on the same box
  - curl -L https://bootstrap.saltstack.com -o install_salt.sh
  - sudo sh install_salt.sh -P stable # use pip for now
  # Set up our installation bits
  - sudo mkdir -p /srv/salt/states
  - sudo cp .travis/minion /etc/salt/minion

install:
  # Copy the states and restart
  - sudo cp -r . /srv/salt/states
  - sudo service salt-minion restart
  - sudo cat /var/log/salt/* || true

script:
  - sudo salt-call state.show_lowstate --local --retcode-passthrough
  - sudo cat /var/log/salt/* || true

notifications:
  email: false
